/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/Demon.glb -t 
*/

import * as THREE from 'three'
import React, { useEffect, useMemo, useRef } from 'react'
import { ThreeElements, useFrame, useThree } from '@react-three/fiber'
import { useGLTF, Bvh } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import vertexShader from "../../shaders/MagicCube/vertex.glsl?raw";
import fragmentShader from "../../shaders/MagicCube/fragment.glsl?raw";

import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useGSAP } from '@gsap/react';

gsap.registerPlugin(ScrollTrigger, useGSAP);


type GLTFResult = GLTF & {
  nodes: {
    Landscape: THREE.Mesh
    Box_001: THREE.Mesh
    Man_1: THREE.Mesh
    Man_2: THREE.Mesh
    Pillar: THREE.Mesh
    Truss_Bridge: THREE.Mesh
    // Allow dynamic access for all Box_NNN debris nodes
    [key: string]: THREE.Mesh | THREE.Object3D
  }
  materials: {
    Mat_Landscape: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    Mat_Man_Body: THREE.MeshStandardMaterial
    InnerEye_Material: THREE.MeshStandardMaterial
    Mat_Glow_Pillar: THREE.MeshStandardMaterial
    Mat_Glow_TrussBridge: THREE.MeshStandardMaterial
    Mat_FloatingDebris: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Demon(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/Demon-transformed.glb') as unknown as GLTFResult
  const { camera, size } = useThree()
  const BoxRef = useRef<THREE.Mesh>(null)
  const TrussRef = useRef<THREE.Mesh>(null)
  const sceneRef = useRef<THREE.Group>(null)
  const parallaxRef = useRef<THREE.Group>(null)
  const debrisRef = useRef<THREE.InstancedMesh>(null)

  // ── Dynamically discover ALL Box_NNN debris nodes from the GLTF ──
  // This captures every box the file actually has, not just Box_002–028.
  const debrisData = useMemo(() => {
    const debrisBoxRegex = /^Box_(\d+)$/
    const results: { position: THREE.Vector3; geometry: THREE.BufferGeometry }[] = []

    Object.entries(nodes).forEach(([key, node]) => {
      const match = debrisBoxRegex.exec(key)
      if (!match) return
      const num = parseInt(match[1], 10)
      if (num === 1) return // skip Box_001 — it has the shader material
      const mesh = node as THREE.Mesh
      if (!mesh.geometry) return
      results.push({ position: mesh.position.clone(), geometry: mesh.geometry })
    })

    console.log(`🗃️ Debris boxes found in GLTF: ${results.length}`)
    return results
  }, [nodes])

  // Use Box_002's geometry as the shared instanced template
  const debrisGeometry = useMemo(
    () => (nodes['Box_002'] as THREE.Mesh)?.geometry,
    [nodes]
  )

  useGSAP(() => {
    const scene = sceneRef.current;
    if (!scene) return;
    console.log(scene.position)

    const tl = gsap.timeline({
      scrollTrigger: {
        trigger: document.body,
        start: "top top",
        end: "bottom bottom",
        scrub: 1,
      }
    });

    tl.to(scene.scale, {
      x: "+=1",
      y: "+=1",
      z: "+=1",
      ease: "power1.inOut",
      duration: 1
    })
      .to(scene.position, {
        y: "-=3",
        ease: "power1.inOut",
        duration: 1
      }, "<")
      .to(scene.rotation, {
        y: "-=1.5",
        ease: "power1.inOut",
      })
      .to(scene.position, {
        x: "-=1.5",
        y: "+=1",
        ease: "power1.inOut",
      }, "<")
      .to(scene.rotation, {
        y: "-=1.5",
        ease: "power1.inOut",
      })
      .to(scene.position, {
        x: "+=1.1",
        y: "+=2",
        ease: "power1.inOut",
      }, "<")
      .to(scene.rotation, {
        y: "-=1.5",
        ease: "power1.inOut",
      })
      .to(scene.position, {
        x: "+=2.1",
        y: "+=0.3",
        ease: "power1.inOut",
      }, "<")
      .to(scene.rotation, {
        y: "-=0.5",
        // x: "-=0.5",
        ease: "power1.inOut",
      })
      .to(scene.rotation, {
        y: "-=1.25",
        // x: "-=0.5",
        ease: "power1.inOut",
      })
      .to(scene.position, {
        x: "-=1.5",
        y: "+=0.5",
        ease: "power1.inOut",
      }, "<")


      ;
  });

  // Stamp each debris instance's world position into the buffer
  useEffect(() => {
    if (!debrisRef.current || debrisData.length === 0) return
    const mesh = debrisRef.current
    const matrix = new THREE.Matrix4()
    debrisData.forEach(({ position }, i) => {
      matrix.setPosition(position)
      mesh.setMatrixAt(i, matrix)
    })
    mesh.instanceMatrix.needsUpdate = true
    // Compute tight bounding sphere for proper frustum culling
    mesh.geometry.computeBoundingSphere()
  }, [debrisData])

  const uniforms = React.useMemo(() => ({
    uResolution: { value: new THREE.Vector2(size.width, size.height) },
    uTime: { value: 0.0 },

    uIOR: { value: 0.07 },  // refraction  0.01–0.20
    uChromatic: { value: 0.012 },  // aberration  0.00–0.03
    uClarity: { value: 0.85 },  // 1=clear, 0=frosted
    uDepthBlend: { value: 0.55 },  // depth absorption mix
    uCausticStr: { value: 0.80 },  // caustic brightness
    uFlowStr: { value: 0.80 },  // inner vein intensity
    uCoreWarmth: { value: 0.75 },  // reserved tint slot
    uBumpStrength: { value: 0.55 },  // surface wave height

    // Frozen ice palette
    uDeepColor: { value: new THREE.Vector3(0.02, 0.10, 0.28) },
    uShallowColor: { value: new THREE.Vector3(0.72, 0.94, 1.00) },
    uCamPos: { value: new THREE.Vector3() },
  }), [])

  useFrame((state, delta) => {
    uniforms.uTime.value = state.clock.getElapsedTime();
    uniforms.uCamPos.value.copy(camera.position);
    uniforms.uResolution.value.set(size.width, size.height);

    const speed = 0.2 // radians per second
    if (BoxRef.current) {
      BoxRef.current.rotation.x += speed * delta;
      BoxRef.current.rotation.z += speed * delta;
    }

    if (TrussRef.current) {
      TrussRef.current.rotation.x += 0.01 * delta;
    }

    if (parallaxRef.current) {
      parallaxRef.current.rotation.y += (state.pointer.x * 0.15 - parallaxRef.current.rotation.y) * 0.06;
      parallaxRef.current.rotation.x += (state.pointer.y * 0.15 - parallaxRef.current.rotation.x) * 0.06;
    }
  })




  return (
    <Bvh firstHitOnly>
      <group ref={parallaxRef}>
        <group ref={sceneRef} {...props} dispose={null}>
          <mesh geometry={nodes.Landscape.geometry} material={materials.Mat_Landscape} position={[0, 0, -0.233]} />
          <mesh ref={BoxRef} name="Box_001" geometry={nodes.Box_001.geometry} position={[-0.009, 1.157, -0.123]} rotation={[0, 0, 0.87]} >
            <shaderMaterial
              vertexShader={vertexShader}
              fragmentShader={fragmentShader}
              uniforms={uniforms}
              transparent={true}
              side={THREE.DoubleSide}
              depthWrite={false}
            />
          </mesh>
          <mesh geometry={nodes.Pillar.geometry} material={materials.Mat_Glow_Pillar} />
          {/* <mesh ref={TrussRef} geometry={nodes.Truss_Bridge.geometry} material={materials.Mat_Glow_TrussBridge} position={[-0.001, 1.981, -1.185]} rotation={[0.1, Math.PI / 2, 0]} /> */}
          <group
            position={[-0.001, 1.981, -1.185]}
            rotation={[0.1, Math.PI / 2, 0]} // 👈 base rotation moved here
          >
            <mesh
              ref={TrussRef}
              geometry={nodes.Truss_Bridge.geometry}
              material={materials.Mat_Glow_TrussBridge}
            />
          </group>
          {/* All debris boxes → 1 instanced draw call */}
          {debrisData.length > 0 && (
            <instancedMesh
              ref={debrisRef}
              args={[debrisGeometry, materials.Mat_FloatingDebris, debrisData.length]}
            />
          )}
          <mesh geometry={nodes.Man_1?.geometry} material={materials.Mat_Man_Body} />
          <mesh geometry={nodes.Man_2?.geometry} material={materials.InnerEye_Material} />
        </group>
      </group>
    </Bvh>
  )
}

useGLTF.preload('/models/Demon-transformed.glb')
